services:
  app:
    build:
      context: ../
      dockerfile: docker/php/php.dockerfile
    restart: always
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./../src:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./../src:/var/www/html
      - ./../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  dbdata:
